# Use the official .NET SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy solution and project files
COPY RythuKooliAPI/RythuKooliAPI.csproj RythuKooliAPI/
COPY Core/Core.csproj Core/
COPY Infrastructure/Infrastructure.csproj Infrastructure/

# Restore dependencies
RUN dotnet restore RythuKooliAPI/RythuKooliAPI.csproj

# Copy the rest of the files
COPY . .

# Build and publish the app
RUN dotnet publish RythuKooliAPI/RythuKooliAPI.csproj -c Release -o /app/publish

# Use the ASP.NET runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# Expose port and set entry point
EXPOSE 80
ENTRYPOINT ["dotnet", "RythuKooliAPI.dll"]
